/**
 *
 *
 * Copyright 2022 Bredec GmbH
 *
 * All rights reserved in Bredec GmbH, authored and generated code (including the
 * selection and arrangement of the source code base regardless of the authorship
 * of individual files), but not including any copyright interest(s) owned by a 
 * third party related to source code or object code authored or generated by
 * non-Bredec personnel. This source code includes Bredec GmbH confidential and/or
 * proprietary information and may include Bredec GmbH trade secrets. Any use
 * disclosure and/or reproduction is prohibited unless authorized in writing.
 *
 *
 */

# =============================================================================================================
# TERRAFORM LOCALS
# Local values are constructed here to avoid redundancies
# =============================================================================================================

locals {
  # Validate if resources are provided or needs to be created.
  create_eks_cluster = var.eks_cluster_name == "" ? true : false

  # Set and construct resource name
  cluster_name       = local.create_eks_cluster ? "she-${var.environment}-eks" : var.eks_cluster_name
  eks_host           = local.create_eks_cluster ? module.eks[0].cluster_endpoint : data.aws_eks_cluster.she-dev-eks[0].endpoint
  kubeconfig-ca-data = local.create_eks_cluster ? module.eks[0].kubeconfig-certificate-authority-data : data.aws_eks_cluster.she-dev-eks[0].certificate_authority[0].data
}


module "eks" {
  count  = local.create_eks_cluster ? 1 : 0
  source = "/home/ec2-user/staging_Terraform/modules/eks"
  #environment                 = var.environment
  app_name = var.app_name
}

data "aws_eks_cluster" "she-dev-eks" {
  count = local.create_eks_cluster ? 0 : 1
  name  = var.eks_cluster_name
  #resource_group_name = var.resource_group_name

  //   depends_on = [
  //     null_resource.enable_addons
  //   ]

}